# Generated by Django 5.2 on 2026-08-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_baseuser_capital_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoporder',
            name='order_mode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stoporder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
